# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = false

# Mod Properties
mod_version = 3.2.1

mod_id = litematica-printer
maven_group = me.aleksilassila
archives_base_name = litematica-printer

# Dependencies (malilib / litematica)
malilib_version = 28fd4dd03a
litematica_version = f735104983

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 1.21.11
minecraft_version = 1.21.11
mappings_version = 1.21.11+build.1

fabric_loader_version = 0.18.2
mod_menu_version = 17.0.0-alpha.1
fabric_api_version = 0.139.4+1.21.11
