# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = false

# Mod Properties
maven_group = me.aleksilassila
mod_id = litematica-printer
mod_name = Litematica Printer
mod_file_name = litematica-printer

# Mod Version
mod_version = 3.6.0

# Dependencies (malilib / litematica)
malilib_version = 0.28.9
litematica_version = 0.27.10

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.1.2
minecraft_version = 26.1.2

fabric_loader_version = 0.19.3
loom_version=1.17-SNAPSHOT
mod_menu_version = 18.0.0
fabric_api_version = 0.154.2+26.1.2
bedrock_miner_version=v1.5.4-mc26.1