pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
//if (file('../hasteless-bedrock-breaker').exists()) {
//    includeBuild('../hasteless-bedrock-breaker')
//}